apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::941377135805:role/eksctl-expense-1-nodegroup-ng-1-NodeInstanceRole-R2t4jmxeaTbA
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-trainee
      userarn: arn:aws:iam::941377135805:user/likhith
      username: likhith
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-16T05:35:34Z"
  name: aws-auth
  namespace: kube-system
  uid: f11c8615-21b1-4780-a8f5-da023d87441e